### ISSUE TITLE
Using with Jade

### ISSUE THREAD

**Issue by Grawl** [tschaub/grunt-newer#44]
I am using `newer` with `contrib-jade` and modified imports does not triggers parent template compile.

`template.jade`

``` jade
p some content
block superblock
    p some block content
```

`modules/sub.jade`

``` jade
append superblock
    p add this to my block
```

And when I change `sub.jade` I want to compile `template.jade` but watcher do not do it. Same problem with `include`. Maybe a problem is in my gruntfile config?

I tried to use `override` function but get `Fatal error: checkForModifiedImports is not defined` on this. Is `checkForModifiedImports` are example function name that I need to write on my own?

My gruntfile: https://gist.github.com/Grawl/0eef67b20a40ec97ace

**Comment by xiaogwu** [comment]
@Grawl 
include true seems to have the same result of compiling everything for me.  For me I was looking for a sass solution so I did:

....
if (detail.task === 'sass')
    include(true);
else
    include(false);

and this resulted in compiling all my scss files instead of just my imports.  I think you have to define your own function.

**Comment by brunowego** [comment]
It works for me:

```js
module.exports = {
  jade: {
    files: ['app/views/pages/{,*/}*.jade'],
    tasks: ['newer:jade:server'],
    options: {
      event: 'changed'
    }
  }
};
```

**Comment by askucher** [comment]
+1
