### ISSUE TITLE
error: The "newer" prefix is not supported for aliases

### ISSUE THREAD

**Issue by liberalist1991** [tschaub/grunt-newer#87]
I use 'load-grunt-tasks' to load all tasks, however when I  add 'grunt-newer'  as tasks: ['newer:to5'], it shows:

   Fatal error: The "newer" prefix is not supported for aliases

**Comment by SudhirVeerakamaraj** [comment]
Facing the same. In nutshell, I was running "grunt default" (which has clean, ES6 transpiling, copy tasks). Created "Watch" task which runs well. However, when I add newer to my watch task. I am getting- the "Newer" prefix is not supported for aliases. As the issue is closed I presume that it was a mistake in config. Can you please let me know what you did to fix this issue?
